### ISSUE TITLE
JS examples broken due to missing package

### ISSUE THREAD

**Issue by secondfolder** [buttplugio/buttplug-developer-guide#39]
The js examples (https://github.com/buttplugio/buttplug-developer-guide/blob/master/examples/javascript/index.html) attempt to import the buttplug-wasm module from this url https://cdn.jsdelivr.net/npm/buttplug-wasm@1.0.7/dist/web/buttplug.js but that url currently returns "Couldn't find the requested release version 1.0.7.".

**Comment by qdot** [comment]
Fixed by #40
